"use client"
import Footer from './components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ['latin'] })
// const  queryClient = new QueryClient()

export const metadata = {
  title: 'KPIM Entrance Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const  queryClient = new QueryClient()
  return (
    <QueryClientProvider client={queryClient}>
      {/* <ReactQueryDevtools /> */}
      <html lang="en" className='bg-light overflow-x-hidden '>
        
        <body className={inter.className}>
        {children}
        <Footer />
        <ReactQueryDevtools />
        
        </body>

      </html>
    </QueryClientProvider>
  )
}
